- name: Install Apache webserver
  hosts: target1
  become: yes
  roles:
    - webserver-var

- name: Install Apache webserver for target2
  hosts: target2
  become: yes
  roles:
    - role: webserver-var
      vars:
        hello_message: 'target2 says hello'